'use server';

/**
 * @fileOverview An AI-powered tool to help users generate refined and engaging profile bios.
 *
 * - improveBio - A function that takes a user's current bio and generates a refined version.
 * - ImproveBioInput - The input type for the improveBio function.
 * - ImproveBioOutput - The return type for the improveBio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveBioInputSchema = z.object({
  currentBio: z
    .string()
    .describe('The user\'s current profile bio that needs to be improved.'),
  desiredTone: z
    .string()
    .optional()
    .describe('The desired tone of the bio (e.g., professional, friendly, humorous).'),
  keywords: z
    .string()
    .optional()
    .describe('Comma-separated keywords to include in the bio.'),
});
export type ImproveBioInput = z.infer<typeof ImproveBioInputSchema>;

const ImproveBioOutputSchema = z.object({
  refinedBio: z
    .string()
    .describe('The refined and engaging profile bio generated by the AI.'),
});
export type ImproveBioOutput = z.infer<typeof ImproveBioOutputSchema>;

export async function improveBio(input: ImproveBioInput): Promise<ImproveBioOutput> {
  return improveBioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveBioPrompt',
  input: {schema: ImproveBioInputSchema},
  output: {schema: ImproveBioOutputSchema},
  prompt: `You are a professional bio writer. You will refine the user's current bio to make it more engaging and effective.

Current Bio: {{{currentBio}}}

{{#if desiredTone}}
Desired Tone: {{{desiredTone}}}
{{/if}}

{{#if keywords}}
Keywords to include: {{{keywords}}}
{{/if}}

Refined Bio:`,
});

const improveBioFlow = ai.defineFlow(
  {
    name: 'improveBioFlow',
    inputSchema: ImproveBioInputSchema,
    outputSchema: ImproveBioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
